"""Add production reporting fields

Revision ID: 467ad9e41d1f
Revises: cfe849de5b09
Create Date: 2026-07-31 13:50:45.280477
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '467ad9e41d1f'
down_revision: str | None = 'cfe849de5b09'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('storage_capacity', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('ram', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('accessories', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('devices', sa.Column('has_invoice', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('devices', sa.Column('has_warranty', sa.Boolean(), nullable=False, server_default='0'))
    op.drop_index(op.f('ix_devices_owner_id'), table_name='devices')
    op.add_column('inspections', sa.Column('functional_tests', sa.JSON(), nullable=True))
    op.add_column('inspections', sa.Column('valuation_breakdown', sa.JSON(), nullable=True))
    op.add_column('inspections', sa.Column('evidence_report', sa.JSON(), nullable=True))
    op.add_column('inspections', sa.Column('trust_score_breakdown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'trust_score_breakdown')
    op.drop_column('inspections', 'evidence_report')
    op.drop_column('inspections', 'valuation_breakdown')
    op.drop_column('inspections', 'functional_tests')
    op.create_index(op.f('ix_devices_owner_id'), 'devices', ['owner_id'], unique=False)
    op.drop_column('devices', 'has_warranty')
    op.drop_column('devices', 'has_invoice')
    op.drop_column('devices', 'accessories')
    op.drop_column('devices', 'ram')
    op.drop_column('devices', 'storage_capacity')
    # ### end Alembic commands ###

