"""Add Inspection persistence fields

Revision ID: 6e64d06552b1
Revises: 467ad9e41d1f
Create Date: 2026-08-01 14:39:45.970676
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6e64d06552b1'
down_revision: str | None = '467ad9e41d1f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('evidence_schema', sa.JSON(), nullable=True))
    op.add_column('inspections', sa.Column('pricing_schema', sa.JSON(), nullable=True))
    op.add_column('inspections', sa.Column('claim_verification_results', sa.JSON(), nullable=True))
    op.add_column('inspections', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.add_column('inspections', sa.Column('device_brand', sa.String(length=120), nullable=True))
    op.add_column('inspections', sa.Column('device_model', sa.String(length=160), nullable=True))
    op.add_column('inspections', sa.Column('device_storage', sa.String(length=50), nullable=True))
    op.add_column('inspections', sa.Column('device_color', sa.String(length=50), nullable=True))
    op.add_column('inspections', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('inspections', sa.Column('quality_metrics', sa.JSON(), nullable=True))
    op.add_column('inspections', sa.Column('tracking_results', sa.JSON(), nullable=True))
    op.add_column('inspections', sa.Column('component_detection', sa.JSON(), nullable=True))
    op.add_column('inspections', sa.Column('damage_detection', sa.JSON(), nullable=True))
    op.add_column('inspections', sa.Column('gemini_output', sa.JSON(), nullable=True))
    op.add_column('inspections', sa.Column('generated_files', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'inspections', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_column('inspections', 'generated_files')
    op.drop_column('inspections', 'gemini_output')
    op.drop_column('inspections', 'damage_detection')
    op.drop_column('inspections', 'component_detection')
    op.drop_column('inspections', 'tracking_results')
    op.drop_column('inspections', 'quality_metrics')
    op.drop_column('inspections', 'status')
    op.drop_column('inspections', 'device_color')
    op.drop_column('inspections', 'device_storage')
    op.drop_column('inspections', 'device_model')
    op.drop_column('inspections', 'device_brand')
    op.drop_column('inspections', 'user_id')
    op.drop_column('inspections', 'claim_verification_results')
    op.drop_column('inspections', 'pricing_schema')
    op.drop_column('inspections', 'evidence_schema')
    # ### end Alembic commands ###

