"""create inspections table

Revision ID: cfe849de5b09
Revises: 20260729_1400
Create Date: 2026-07-29 21:49:38.460508
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cfe849de5b09'
down_revision: str | None = '20260729_1400'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('inspection_score', sa.Integer(), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('estimated_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('detected_issues', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_inspection_reports_device_id'), table_name='inspection_reports')
    op.drop_table('inspection_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_reports',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('device_id', sa.CHAR(length=32), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('detected_defects', sa.JSON(), nullable=False),
    sa.Column('inspection_summary', sa.TEXT(), nullable=False),
    sa.Column('estimated_price', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('trust_score', sa.INTEGER(), nullable=False),
    sa.Column('inspection_score', sa.INTEGER(), nullable=False),
    sa.Column('confidence_score', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_reports_device_id'), 'inspection_reports', ['device_id'], unique=False)
    op.drop_table('inspections')
    # ### end Alembic commands ###

