"use client"
import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Download, Share2, UploadCloud, Store } from "lucide-react"
import { reportApi } from "@/services/report.api"

export function ActionPanel({ reportId }: { reportId: string }) {
  const [isPublishing, setIsPublishing] = useState(false)
  const [isSharing, setIsSharing] = useState(false)

  const handlePublish = async () => {
    setIsPublishing(true)
    await reportApi.publishReport(reportId)
    setIsPublishing(false)
    // Future: Redirect to Marketplace
  }

  const handleShare = async () => {
    setIsSharing(true)
    await reportApi.shareReport(reportId)
    setIsSharing(false)
    // Future: Trigger share dialog
  }

  return (
    <div className="bg-card border border-border/60 rounded-2xl p-6 shadow-md flex flex-col gap-3">
      <h3 className="font-bold text-lg mb-2">Actions</h3>
      
      <Button 
        size="lg" 
        className="w-full bg-primary hover:bg-primary/90 shadow-md group"
        onClick={handlePublish}
        isLoading={isPublishing}
      >
        <Store className="w-4 h-4 mr-2" />
        Publish to Marketplace
      </Button>

      <div className="grid grid-cols-2 gap-3 mt-1">
        <Button 
          variant="outline" 
          className="w-full"
          onClick={handleShare}
          isLoading={isSharing}
        >
          <Share2 className="w-4 h-4 mr-2" />
          Share
        </Button>
        <Button variant="outline" className="w-full">
          <Download className="w-4 h-4 mr-2" />
          PDF
        </Button>
      </div>

      <p className="text-[10px] text-center text-muted-foreground mt-4 uppercase tracking-wider font-semibold">
        Report generated by Satya Moolya AI
      </p>
    </div>
  )
}
